version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: myapp_mongo_vite
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: myapp_server_vite
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  caddy:
    image: caddy:latest
    container_name: myapp_caddy_vite
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./client/dist:/srv/app/client/dist
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server

volumes:
  mongo-data:
  caddy_data:
  caddy_config:
