name: Build & Deploy Vite App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install client dependencies
      working-directory: ./client
      run: npm ci

    - name: Build client
      working-directory: ./client
      run: npm run build

    - name: Upload dist to server
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "mkdir -p /home/ubuntu/node-vite-with-mongodb/client/dist"
        rsync -avz --delete ./client/dist/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/ubuntu/node-vite-with-mongodb/client/dist

    - name: Upload server & config files
      run: |
        rsync -avz --delete ./server/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/ubuntu/node-vite-with-mongodb/server
        rsync -avz docker-compose.yml Caddyfile ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/ubuntu/node-vite-with-mongodb/

    - name: Rebuild and restart Docker Compose
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd /home/ubuntu/node-vite-with-mongodb
          docker-compose pull
          docker-compose build
          docker-compose down
          docker-compose up -d
        EOF
